version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-spring
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: rental
    ports:
      - "5432:5432"
    networks:
      - spring-network

  spring-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-spring:5432/rental
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge
