version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-spring
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: rental
    ports:
      - "5432:5432"
